Corrected scripts

diff --git a/home/.chezmoiscripts/run_after_installpackages_zsh.tmpl b/home/.chezmoiscripts/run_after_installpackages_zsh.tmpl
--- a/home/.chezmoiscripts/run_after_installpackages_zsh.tmpl
+++ b/home/.chezmoiscripts/run_after_installpackages_zsh.tmpl
@@ -5,13 +5,24 @@ zsh=(
 	fzf
 )
 
-SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-
-# Change the working directory to the parent directory of the script
-PARENT_DIR="$SCRIPT_DIR/.."
-cd "$PARENT_DIR" || exit 1
-
-source "$(dirname "$(readlink -f "$0")")/global_functions.sh"
+install_package() {
+  # Checking if package is already installed
+  if paru -Q "$1" &>> /dev/null ; then
+    echo -e "${OK} $1 is already installed. Skipping..."
+  else
+    # Package not installed
+    echo -e "${NOTE} Installing $1 ..."
+    paru -S --noconfirm "$1" 2>&1 | tee -a "$LOG"
+    # Making sure package is installed
+    if paru -Q "$1" &>> /dev/null ; then
+      echo -e "\e[1A\e[K${OK} $1 was installed."
+    else
+      # Something is missing, exiting to review log
+      echo -e "\e[1A\e[K${ERROR} $1 failed to install :( , please check the install.log. You may need to install manually! Sorry I have tried :("
+      exit 1
+    fi
+  fi
+}
 
 # Installing zsh packages
 printf "${NOTE} Installing core zsh packages...${RESET}\n"
