Removed old package install

diff --git a/home/.chezmoiscripts/run_onchange_after_0installpackages_zsh.sh.tmpl b/home/.chezmoiscripts/run_onchange_after_0installpackages_zsh.sh.tmpl
--- a/home/.chezmoiscripts/run_onchange_after_0installpackages_zsh.sh.tmpl
+++ b/home/.chezmoiscripts/run_onchange_after_0installpackages_zsh.sh.tmpl
@@ -7,6 +7,25 @@ zsh=(
 	fzf
 )
 
+install_package() {
+  # Checking if package is already installed
+  if paru -Q "$1" &>> /dev/null ; then
+    echo -e "${OK} $1 is already installed. Skipping..."
+  else
+    # Package not installed
+    echo -e "${NOTE} Installing $1 ..."
+    paru -S --noconfirm "$1" 2>&1 | tee -a "$LOG"
+    # Making sure package is installed
+    if paru -Q "$1" &>> /dev/null ; then
+      echo -e "\e[1A\e[K${OK} $1 was installed."
+    else
+      # Something is missing, exiting to review log
+      echo -e "\e[1A\e[K${ERROR} $1 failed to install :( , please check the install.log. You may need to install manually! Sorry I have tried :("
+      exit 1
+    fi
+  fi
+}
+
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 source "$SCRIPT_DIR/.globalscripts/global_functions.sh"
